# Generated by Django 5.1.5 on 2025-01-15 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_table', models.CharField(max_length=50)),
                ('archive_date', models.DateTimeField(auto_now_add=True)),
                ('archive_user', models.IntegerField()),
                ('archive_reason', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_by_user', models.IntegerField()),
                ('is_archived', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Coding_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_by_user', models.IntegerField()),
                ('is_archived', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cohorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_name', models.CharField(max_length=50)),
                ('added_by_user', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('added_by_user', models.IntegerField()),
                ('is_archived', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Note_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_category_name', models.CharField(max_length=50)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_by_user', models.IntegerField()),
                ('is_archived', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=100)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_by_user', models.IntegerField()),
                ('is_archived', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=220)),
                ('user_id', models.IntegerField()),
                ('anonymous', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('added_by_user', models.IntegerField()),
                ('likes_count', models.IntegerField()),
                ('is_archived', models.BooleanField()),
                ('archive_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archived_notes', to='workshops.archive_details')),
                ('coding_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_notes', to='workshops.coding_language')),
                ('note_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='workshops.note_category')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.CharField(max_length=1000)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('image_url', models.URLField(max_length=2000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.IntegerField()),
                ('is_archived', models.BooleanField()),
                ('archive_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archived_workshops', to='workshops.archive_details')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='workshops.category')),
                ('coding_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_workshops', to='workshops.coding_language')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_workshops', to='workshops.location')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_workshops', to='workshops.organisation')),
            ],
        ),
    ]
