# Generated by Django 5.1 on 2025-01-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_archived',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='coding_language',
            name='is_archived',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='cohorts',
            name='is_archived',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_archived',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='note_category',
            name='is_archived',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='notes',
            name='anonymous',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='notes',
            name='is_archived',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='notes',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='is_archived',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='is_archived',
            field=models.BooleanField(default=0),
        ),
    ]
