# Generated by Django 5.1.5 on 2025-01-16 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_alter_archive_details_archive_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='workshop_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='workshops.workshop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_notes', to='workshops.note_category'),
        ),
    ]
