# Generated by Django 5.1.5 on 2025-01-16 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_notes_workshop_id_alter_notes_note_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='archive_id',
            new_name='archive',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='workshop_id',
            new_name='workshop',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='archive_id',
            new_name='archive',
        ),
    ]
